version: '3.8'
services:
  catalogdb:
    container_name: catelogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catelogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=12345678
      - PSOTGRES_DB=discountdb
  identitydb:
      container_name: identitydb
      restart: always
      ports:
        - "1433:1433"
      volumes:
        - Identitydb_volume:/var/opt/mssql
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password12*    
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=Password12*
  catalog.api:
    container_name: catalog.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL:http://identityserver.api:5001
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb; User=sa; Password=Password12*"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL:http://identityserver.api:5001
      - RedisSettings:Port=6379
      - RedisSettings:basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL:http://identityserver.api:5001    
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: E:\photos
        target: /app/wwwroot/photos
