version: '3.8'
services:  
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - Identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*    
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "1445:1433"
    volumes:
      - productdb_volume:/var/opt/mssql
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=Password123 
  identityserverApi:
    container_name: identityserverApi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb; User=sa; Password=Password12*"
    ports:
      - "5001:80"
    depends_on:
      - identitydb  
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserverApi      
      - "ConnectionStrings.DefaultConnection=Server=productdb,1445;Database=productdb;User=sa;Password=Password123"
    ports:
      - "5017:80"
    depends_on:
      - productdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://identityserverApi 
    ports:
      - "5000:80"
      