version: '3.8'
services:  
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  productdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/LgwCase.IdentityServer/Dockerfile 
  product.api:
    image: product_api_image
    build:
      context: .
      dockerfile: Services/Product/LgwCase.Services.Product.API/Dockerfile
  gateway.api:
    image: gateway_api_image
    build:
      context: .
      dockerfile: GateWays/LgwCase.Gateway/Dockerfile  
volumes:
  Identitydb_volume:
  productdb_volume:

  


